[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Andrei Sousa <sousandrei@gmail.com>"]
edition = "2018"


[dependencies]
criterion = "0.3.3"
regex = "1.4.2"

[[bench]]
name = "bench"
harness = false
