name: CI

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo Build
        run: cargo build --release

      - name: Cargo Test
        run: cargo test
